version: 2.1

executors:
  golang:
    working_directory: /go/src/moul.io/godev
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"

orbs:
  codecov: codecov/codecov@1.0.5
  moul: moul/build@1.10.0
  retry: moul/retry@0.6.0
  tools: gotest/tools@0.0.10

jobs:
  go-build:
    executor: golang
    steps:
      - checkout
      - retry/install
      - tools/mod-download
      - tools/mod-tidy-check
      - run: retry -m 3 make unittest
      - moul/install_golangci-lint
      - run: PATH=$PATH:$(pwd)/bin retry -m 3 make lint
      - codecov/upload:
          file: coverage.txt

workflows:
  main:
    jobs:
      - go-build
